const matchesData = [
  // Samedi, 26 avril 2025
  { date: '2025-04-26', category: 'L1 DAME', homeTeam: 'FALCONS', awayTeam: 'FAP', homeScore: 26, awayScore: 77, status: 'completed' },
  { date: '2025-04-26', category: 'L1 DAME', homeTeam: 'LENA', awayTeam: 'ONYX', homeScore: 46, awayScore: 66, status: 'completed' },
  { date: '2025-04-26', category: 'L1 DAME', homeTeam: 'MARIK YD2', awayTeam: 'AS KEEP', homeScore: 24, awayScore: 87, status: 'completed' },
  { date: '2025-04-26', category: 'L1 DAME', homeTeam: 'OVERDOSE', awayTeam: 'MC NOAH', homeScore: 55, awayScore: 37, status: 'completed' },
  { date: '2025-04-26', category: 'L1 MESSIEUR', homeTeam: 'ONYX', awayTeam: '512 SA', homeScore: 48, awayScore: 65, status: 'completed' },
  { date: '2025-04-26', category: 'L1 MESSIEUR', homeTeam: 'ALPH', awayTeam: 'ANGELS', homeScore: 66, awayScore: 36, status: 'completed' },
  { date: '2025-04-26', category: 'L1 MESSIEUR', homeTeam: 'FALCONS', awayTeam: 'WILDCATS', homeScore: 60, awayScore: 55, status: 'completed' },
  { date: '2025-04-26', category: 'L1 MESSIEUR', homeTeam: 'BEAC', awayTeam: 'ETOUTI', homeScore: 113, awayScore: 44, status: 'completed' },
  { date: '2025-04-26', category: 'L1 MESSIEUR', homeTeam: 'FAP', awayTeam: 'MC NOAH', homeScore: 62, awayScore: 59, status: 'completed' },

  // Samedi, 10 mai 2025
  { date: '2025-05-10', category: 'U18 FILLES', homeTeam: 'SANTA B.', awayTeam: 'FUSEE', homeScore: 17, awayScore: 45, status: 'completed' },
  { date: '2025-05-10', category: 'L2A MESSIEUR', homeTeam: 'ALPH2', awayTeam: 'MENDONG', homeScore: 42, awayScore: 47, status: 'completed' },
  { date: '2025-05-10', category: 'L2A MESSIEUR', homeTeam: 'LENA', awayTeam: 'KLOES YD2', homeScore: 37, awayScore: 41, status: 'completed' },
  { date: '2025-05-10', category: 'L2B MESSIEUR', homeTeam: 'APEJES2', awayTeam: 'MBALMAYO', homeScore: 25, awayScore: 60, status: 'completed' },
  { date: '2025-05-10', category: 'L2B MESSIEUR', homeTeam: 'PHISLAMA', awayTeam: 'MBALMAYO', homeScore: 49, awayScore: 73, status: 'completed' },
  { date: '2025-05-10', category: 'L1 DAME', homeTeam: 'FAP2', awayTeam: 'MC NOAH', homeScore: 38, awayScore: 26, status: 'completed' },
  { date: '2025-05-10', category: 'L1 MESSIEUR', homeTeam: 'MC NOAH', awayTeam: 'NYBA', homeScore: 71, awayScore: 58, status: 'completed' },

  // Dimanche, 11 mai 2025
  { date: '2025-05-11', category: 'L2B MESSIEUR', homeTeam: 'MBOA BB', awayTeam: 'SANTA B.', homeScore: 20, awayScore: 0, status: 'completed' },
  { date: '2025-05-11', category: 'L2B MESSIEUR', homeTeam: 'PHISLAMA', awayTeam: 'HAND OF GOD', homeScore: 52, awayScore: 59, status: 'completed' },
  { date: '2025-05-11', category: 'L2A MESSIEUR', homeTeam: 'MESSASSI', awayTeam: 'AS KEEP', homeScore: 71, awayScore: 73, status: 'completed' },
  { date: '2025-05-11', category: 'L2A MESSIEUR', homeTeam: 'ALL SPORT', awayTeam: 'BOFIA', homeScore: 49, awayScore: 37, status: 'completed' },
  { date: '2025-05-11', category: 'L2A MESSIEUR', homeTeam: 'SEED EXP.', awayTeam: 'FUSEE', homeScore: 29, awayScore: 50, status: 'completed' },
  { date: '2025-05-11', category: 'L2A MESSIEUR', homeTeam: 'MARY JO', awayTeam: 'APEJES', homeScore: 51, awayScore: 70, status: 'completed' },
  { date: '2025-05-11', category: 'L1 DAME', homeTeam: 'ONYX', awayTeam: 'OVERDOSE', homeScore: 41, awayScore: 65, status: 'completed' },
  { date: '2025-05-11', category: 'L1 DAME', homeTeam: 'LENA', awayTeam: 'AS KEEP2', homeScore: 24, awayScore: 32, status: 'completed' },
  { date: '2025-05-11', category: 'L1 MESSIEUR', homeTeam: 'ETOUTI', awayTeam: 'WILDCATS', homeScore: 61, awayScore: 79, status: 'completed' },
  { date: '2025-05-11', category: 'L1 MESSIEUR', homeTeam: 'FALCONS', awayTeam: 'ANGELS', homeScore: 67, awayScore: 78, status: 'completed' },

  // Samedi, 17 mai 2025
  { date: '2025-05-17', category: 'L2B MESSIEUR', homeTeam: 'HAND OF GOD', awayTeam: 'APEJES2', homeScore: 48, awayScore: 45, status: 'completed' },
  { date: '2025-05-17', category: 'L2B MESSIEUR', homeTeam: 'WILDCATS', awayTeam: 'EAST BB', homeScore: 64, awayScore: 63, status: 'completed' },
  { date: '2025-05-17', category: 'L2B MESSIEUR', homeTeam: 'PHYSILAMA', awayTeam: 'TEAM K SPORT', homeScore: 31, awayScore: 63, status: 'completed' },
  { date: '2025-05-17', category: 'L2B MESSIEUR', homeTeam: 'SANTA BARBARA', awayTeam: 'OVENG BB', homeScore: 19, awayScore: 74, status: 'completed' },
  { date: '2025-05-17', category: 'L2A MESSIEUR', homeTeam: 'EXPENDABLES', awayTeam: 'LENA', homeScore: 46, awayScore: 39, status: 'completed' },
  { date: '2025-05-17', category: 'L2A MESSIEUR', homeTeam: 'KLOES YD2', awayTeam: 'JOAKIM BB', homeScore: 40, awayScore: 39, status: 'completed' },
  { date: '2025-05-17', category: 'L1 DAME', homeTeam: 'AS KEEP2', awayTeam: 'MC NOAH', homeScore: 27, awayScore: 48, status: 'completed' },
  { date: '2025-05-17', category: 'L1 DAME', homeTeam: 'LENA', awayTeam: 'FALCONS', homeScore: 34, awayScore: 32, status: 'completed' },
  { date: '2025-05-17', category: 'L1 MESSIEUR', homeTeam: 'ETOUTI', awayTeam: '512 SA', homeScore: 52, awayScore: 62, status: 'completed' },
  { date: '2025-05-17', category: 'L1 MESSIEUR', homeTeam: 'NYBA', awayTeam: 'ACPBA', homeScore: 57, awayScore: 70, status: 'completed' },
  { date: '2025-05-17', category: 'L1 MESSIEUR', homeTeam: 'ALPH', awayTeam: 'FALCONS', homeScore: 53, awayScore: 37, status: 'completed' },

  // Dimanche, 18 mai 2025
  { date: '2025-05-18', category: 'L2B MESSIEUR', homeTeam: 'TEAM K SPORT', awayTeam: 'WILDCATS2', homeScore: 74, awayScore: 65, status: 'completed' },
  { date: '2025-05-18', category: 'L2B MESSIEUR', homeTeam: 'EAST BB', awayTeam: 'SANTA BARBARA', homeScore: 59, awayScore: 29, status: 'completed' },
  { date: '2025-05-18', category: 'L2B MESSIEUR', homeTeam: 'MBOA BB', awayTeam: 'PHYSILAMA', homeScore: 20, awayScore: 0, status: 'completed' },
  { date: '2025-05-18', category: 'L2B MESSIEUR', homeTeam: 'OVENG BB', awayTeam: 'HAND OF GOD', homeScore: 72, awayScore: 74, status: 'completed' },
  { date: '2025-05-18', category: 'L2A MESSIEUR', homeTeam: 'BOFIA', awayTeam: 'MARY JO', homeScore: 27, awayScore: 59, status: 'completed' },
  { date: '2025-05-18', category: 'L2A MESSIEUR', homeTeam: 'ALPH2', awayTeam: 'WOLVES2', homeScore: 85, awayScore: 49, status: 'completed' },
  { date: '2025-05-18', category: 'L2A MESSIEUR', homeTeam: 'MENDONG', awayTeam: 'MESSASSI', homeScore: 84, awayScore: 54, status: 'completed' },
  { date: '2025-05-18', category: 'L2A MESSIEUR', homeTeam: 'MC NOAH2', awayTeam: 'WOLVES1', homeScore: 49, awayScore: 56, status: 'completed' },
  { date: '2025-05-18', category: 'L1 DAME', homeTeam: 'ONYX', awayTeam: 'MARIK KLOES', homeScore: 85, awayScore: 16, status: 'completed' },
  { date: '2025-05-18', category: 'L1 DAME', homeTeam: 'FAP2', awayTeam: 'FAP', homeScore: 26, awayScore: 51, status: 'completed' },
  { date: '2025-05-18', category: 'L1 DAME', homeTeam: 'OVERDOSE', awayTeam: 'AS KEEP', homeScore: 58, awayScore: 57, status: 'completed' },
  { date: '2025-05-18', category: 'L1 MESSIEUR', homeTeam: 'MC NOAH', awayTeam: 'ONYX', homeScore: 60, awayScore: 54, status: 'completed' },
  { date: '2025-05-18', category: 'L1 MESSIEUR', homeTeam: 'FRIENDSHIP', awayTeam: 'BEAC', homeScore: 44, awayScore: 83, status: 'completed' },
  { date: '2025-05-18', category: 'L1 MESSIEUR', homeTeam: 'LIGHT ACADEMY', awayTeam: 'ETOUTI', homeScore: 71, awayScore: 62, status: 'completed' },
  { date: '2025-05-18', category: 'L1 MESSIEUR', homeTeam: 'FAP', awayTeam: 'WILDCATS', homeScore: 71, awayScore: 51, status: 'completed' },

  // Samedi, 22 février 2025
  { date: '2025-02-22', category: 'L2 MESSIEUR', homeTeam: 'SEED EXP.', awayTeam: 'APEJES', homeScore: 24, awayScore: 93, status: 'completed' },
  { date: '2025-02-22', category: 'L2 MESSIEUR', homeTeam: 'MESSASSI', awayTeam: 'JOAKIM', homeScore: 52, awayScore: 49, status: 'completed' },
  { date: '2025-02-22', category: 'DAMES', homeTeam: 'ASKEEP 2', awayTeam: 'ONYX', homeScore: 22, awayScore: 47, status: 'completed' },
  { date: '2025-02-22', category: 'L1 MESSIEUR', homeTeam: 'FAP', awayTeam: 'ONYX', homeScore: 55, awayScore: 39, status: 'completed' },
  { date: '2025-02-22', category: 'L1 MESSIEUR', homeTeam: 'MC NOAH', awayTeam: 'ACPBA', homeScore: 67, awayScore: 69, status: 'completed' },
  { date: '2025-02-22', category: 'L1 MESSIEUR', homeTeam: 'NYBA', awayTeam: 'BEAC', homeScore: 40, awayScore: 90, status: 'completed' },

  // Dimanche, 23 février 2025
  { date: '2025-02-23', category: 'U18 FILLES', homeTeam: 'FX VOGT', awayTeam: 'SANTA BARBARA', homeScore: 32, awayScore: 17, status: 'completed' },
  { date: '2025-02-23', category: 'U18 FILLES', homeTeam: 'PLAY2LEAD', awayTeam: '3A BB', homeScore: 33, awayScore: 34, status: 'completed' },
  { date: '2025-02-23', category: 'U18 GARCONS', homeTeam: 'FX VOGT 2', awayTeam: 'DREAM BB', homeScore: 22, awayScore: 54, status: 'completed' },
  { date: '2025-02-23', category: 'U18 GARCONS', homeTeam: 'MENDONG', awayTeam: 'GREEN CITY', homeScore: 44, awayScore: 51, status: 'completed' },
  { date: '2025-02-23', category: 'U18 GARCONS', homeTeam: 'ALPH 1', awayTeam: 'MC NOAH', homeScore: 34, awayScore: 75, status: 'completed' },
  { date: '2025-02-23', category: 'U18 GARCONS', homeTeam: '512 SA', awayTeam: 'PLAY2LEAD', homeScore: 48, awayScore: 34, status: 'completed' },
  { date: '2025-02-23', category: 'U18 GARCONS', homeTeam: 'PEPINIERE', awayTeam: 'FRIENDSHIP', homeScore: 43, awayScore: 41, status: 'completed' },
  { date: '2025-02-23', category: 'U18 GARCONS', homeTeam: 'WILDCATS', awayTeam: 'ONYX', homeScore: 20, awayScore: 0, status: 'completed' },
  { date: '2025-02-23', category: 'L2 MESSIEUR', homeTeam: 'JOAKIM', awayTeam: 'ASKEEP', homeScore: 39, awayScore: 30, status: 'completed' },
  { date: '2025-02-23', category: 'L2 MESSIEUR', homeTeam: 'ALL SPORT', awayTeam: 'LAMARFEE', homeScore: 50, awayScore: 64, status: 'completed' },
  { date: '2025-02-23', category: 'L2 MESSIEUR', homeTeam: 'EXPENDABLES', awayTeam: 'ALPH 2', homeScore: 63, awayScore: 34, status: 'completed' },
  { date: '2025-02-23', category: 'L2 MESSIEUR', homeTeam: 'MSA', awayTeam: 'APEJES', homeScore: 26, awayScore: 49, status: 'completed' },
  { date: '2025-02-23', category: 'DAMES', homeTeam: 'AS KEEP', awayTeam: 'MC NOAH', homeScore: 56, awayScore: 33, status: 'completed' },
  { date: '2025-02-23', category: 'L1 MESSIEUR', homeTeam: 'WILDCATS', awayTeam: '512 SA', homeScore: 60, awayScore: 54, status: 'completed' },
  { date: '2025-02-23', category: 'L1 MESSIEUR', homeTeam: 'LIGHT ACADEMY', awayTeam: 'FALCONS', homeScore: 59, awayScore: 75, status: 'completed' },
  { date: '2025-02-23', category: 'L1 MESSIEUR', homeTeam: 'ALPH', awayTeam: 'FRIENDSHIP', homeScore: 79, awayScore: 66, status: 'completed' },

  // Samedi, 01 mars 2025
  { date: '2025-03-01', category: 'U18 FILLES', homeTeam: 'FUSEE', awayTeam: 'FAP', homeScore: 40, awayScore: 74, status: 'completed' },
  { date: '2025-03-01', category: 'U18 FILLES', homeTeam: 'PLAY2LEAD', awayTeam: 'MARIK KLOES', homeScore: 27, awayScore: 42, status: 'completed' },
  { date: '2025-03-01', category: 'U18 GARCONS', homeTeam: 'ACPBA', awayTeam: 'COSBIE', homeScore: 40, awayScore: 38, status: 'completed' },
  { date: '2025-03-01', category: 'L2B MESSIEUR', homeTeam: 'MBALMAYO BB', awayTeam: 'HAND OF GOD', homeScore: 45, awayScore: 42, status: 'completed' },
  { date: '2025-03-01', category: 'L2A MESSIEUR', homeTeam: 'KLOES YD2', awayTeam: 'ALPH2', homeScore: 48, awayScore: 47, status: 'completed' },
  { date: '2025-03-01', category: 'L2A MESSIEUR', homeTeam: 'MARY JO', awayTeam: 'MSA', homeScore: 53, awayScore: 38, status: 'completed' },
  { date: '2025-03-01', category: 'L2A MESSIEUR', homeTeam: 'MENDONG', awayTeam: 'LENA', homeScore: 60, awayScore: 41, status: 'completed' },
  { date: '2025-03-01', category: 'L2A MESSIEUR', homeTeam: 'SEED EXP.', awayTeam: 'MARFEE', homeScore: 17, awayScore: 56, status: 'completed' },
  { date: '2025-03-01', category: 'L1 MESSIEUR', homeTeam: 'FALCONS', awayTeam: 'FRIENDSHIP', homeScore: 69, awayScore: 37, status: 'completed' },
  { date: '2025-03-01', category: 'L1 MESSIEUR', homeTeam: '512 SA', awayTeam: 'NYBA', homeScore: 51, awayScore: 47, status: 'completed' },

  // Additional matches from seedMatches.ts
  { date: '2025-02-15', category: 'U18 FILLES', homeTeam: 'SANTA BARBARA FILLES', awayTeam: 'PLAY2LEAD FILLES', homeScore: 37, awayScore: 31, status: 'completed' },
  { date: '2025-02-15', category: 'U18 GARCONS', homeTeam: '512 SA U18', awayTeam: 'MC NOAH U18', homeScore: 51, awayScore: 78, status: 'completed' },
  { date: '2025-02-15', category: 'L2A MESSIEUR', homeTeam: 'SEED EXPENDABLE', awayTeam: 'WOLVES1', homeScore: 44, awayScore: 71, status: 'completed' },
  { date: '2025-02-15', category: 'L1 MESSIEUR', homeTeam: 'ONYX MESSIEURS', awayTeam: 'FRIENDSHIP MESSIEURS', homeScore: 47, awayScore: 52, status: 'completed' },
  { date: '2025-02-16', category: 'U18 FILLES', homeTeam: 'FX VOGT FILLES', awayTeam: 'OLYMPIQUE DE MEYO', homeScore: 48, awayScore: 0, status: 'completed' },
  { date: '2025-02-16', category: 'U18 GARCONS', homeTeam: 'PEPINIERE', awayTeam: 'MESSASSI U18', homeScore: 38, awayScore: 65, status: 'completed' },
  { date: '2025-02-16', category: 'U18 GARCONS', homeTeam: 'PLAY2LEAD GARCONS', awayTeam: 'ONYX U18', homeScore: 56, awayScore: 63, status: 'completed' },
  { date: '2025-02-16', category: 'L2A MESSIEUR', homeTeam: 'EXPENDABLES', awayTeam: 'MESSASSI L2A', homeScore: 90, awayScore: 56, status: 'completed' },
  { date: '2025-02-16', category: 'L2A MESSIEUR', homeTeam: 'MSA', awayTeam: 'LA MARFEE', homeScore: 40, awayScore: 51, status: 'completed' },
  { date: '2025-02-16', category: 'L1 MESSIEUR', homeTeam: '512 SA', awayTeam: 'MC NOAH MESSIEURS', homeScore: 44, awayScore: 79, status: 'completed' },
];

// ... existing code ... 